# Generated by Django 4.0.5 on 2022-08-02 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0007_userprofile_id_alter_userprofile_user'),
        ('user_dashboard', '0002_alter_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=50)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=10)),
                ('payment_id', models.CharField(default='', max_length=22)),
                ('order_id', models.CharField(max_length=24)),
                ('verification_signature', models.CharField(default='', max_length=100)),
                ('verification_status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_dashboard.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.userprofile')),
            ],
        ),
    ]
