# Generated by Django 4.0.5 on 2022-07-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('project', models.IntegerField()),
                ('amount', models.IntegerField(default=50)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=10)),
                ('payment_id', models.CharField(default='', max_length=18)),
                ('order_id', models.CharField(max_length=20)),
                ('verification_signature', models.CharField(default='', max_length=64)),
                ('verification_status', models.BooleanField(default=False)),
            ],
        ),
    ]
