# Generated by Django 4.0.5 on 2022-07-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='order_id',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='payment_id',
            field=models.CharField(default='', max_length=22),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='verification_signature',
            field=models.CharField(default='', max_length=100),
        ),
    ]
