# Generated by Django 4.0.5 on 2022-08-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_alter_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='projects/%Y/%m'),
        ),
        migrations.AddField(
            model_name='project',
            name='raised',
            field=models.IntegerField(default=0),
        ),
    ]
